from lib.Exceptions.Exceptions import (BadResponse,
                                       FailedSessionInit,
                                       FailedToBuildPage,
                                       GetFirstPageError, GetPageCountError,
                                       GetPageError, GetSourceError,
                                       LoadingBaseDataError,
                                       MaxRetriesReached, ParsePageError,
                                       ProcessPagesError, ProductInfoError,
                                       ProductPageParseError,
                                       ProductScrapeError)
